variables:
  - group: Publishing Secrets

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: npm i
    displayName: 'Install npm dependencies'

  - script: npx semantic-release
    displayName: 'Release'
    env:
      GH_TOKEN: $(GH_TOKEN)
NPM_TOKEN: $(NPM_TOKEN)
