variables:
  - group: Publishing Secrets

  - name: PIPELINE_ARTIFACT_NAME
    value: 'spawnmp-build'

trigger:
  - master

jobs:
  - job: Build
    pool:
      vmImage: 'windows-2019'
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)

      - script: npm i
        displayName: 'Install npm dependencies'

      - script: npm run static
        displayName: 'Static analysis'

      - script: npm run build
        displayName: 'Compile'

      - publish: $(Agent.BuildDirectory)
        # We only need one build in the matrix to do this.
        condition: eq(variables['node_version'], '12.x'))
        artifact: $(PIPELINE_ARTIFACT_NAME)

  # ------ #

  - job: Release
    dependsOn: build
    steps:
      - checkout: none

      - download: current
        artifact: $(PIPELINE_ARTIFACT_NAME)

      - script: npx semantic-release
        displayName: 'Release'
        env:
          GH_TOKEN: $(GH_TOKEN)
          NPM_TOKEN: $(NPM_TOKEN)
